WIP [CP-1932] Investigate pay360 skin management api
CPlus/paypoint-blue pull request #3
Opened 2016-10-13 08:44 UTC by Sysqa

2016-10-13 09:39 UTC, lackac requested changes
I like that you made an effort to keep with the conventions of the repo. There are still some improvements to be made. I haven't checked the functionality yet, so let me know if you have issues there.

2016-10-13 09:39 UTC, lackac commented on lib/paypoint/blue/hosted.rb
> +  def retrieve_skin_list
If you look into `api.rb` you'll see that the convention was to use `<action>_<something>` naming for methods that change state (i.e. use one of the HTTP verbs `POST`, `PUT`, or `DELETE`) and `<noun>` naming for those that only retrieve something (i.e. user the HTTP method `GET`). In keeping with this, let's call this method simply `#skins`.

2016-10-13 09:39 UTC, lackac commented on lib/paypoint/blue/hosted.rb
> +  def download_skin(skin_id)
I would prefer to add an optional argument for providing a path where the skin should be downloaded. Let's default it to `"."` though.

2016-10-13 09:39 UTC, lackac commented on lib/paypoint/blue/hosted.rb
> +  def upload_skin(file, params)
Let's make params optional by using the keyword arguments splat operator. Also, if the name is indeed required (please verify by testing, because the API docs are not always accurate) then we should list it as a required keyword argument:

```ruby
def upload_skin(file, name:, **params)
  # ...
  request.url "skins/#{inst_id}/create", params.merge(name: name)
```

2016-10-13 09:39 UTC, lackac commented on lib/paypoint/blue/hosted.rb
> +  # Updating a skin name and description only
This description is a bit confusing. Maybe something like, "Update the skin by uploading a new zip file. The method may also be used to update only the name and description of an existing skin."

2016-10-13 09:39 UTC, lackac commented on lib/paypoint/blue/hosted.rb
> +  def replace_skin(skin_id, **arguments)
To keep the convention of the other methods, let's call the options arguments `params`. Furthermore, it helps to separate `file` as a keyword argument so that you don't have to remove it from `params`. The method would look like this:

```ruby
def replace_skin(skin_id, file: nil, **params)
  client.put do |request|
    request.url "skins/#{skin_id}", params
    if file
      request.headers["Content-Type"] = "application/zip"
      request.body = File.read(file)
    end
  end
end
```

2016-10-13 10:31 UTC, Sysqa commented on lib/paypoint/blue/hosted.rb
> +  def upload_skin(file, params)
If you don't provide the name the api throw an error

2016-10-14 11:01 UTC, Sysqa commented
@lackac Please check the changes.

2016-10-18 16:55 UTC, lackac approved these changes
Good work. I especially appreciate that you added such a good test coverage for the new methods.

2016-10-18 16:56 UTC, merged